<?php defined('SYSPATH') or die('No direct script access.'); ?>

2017-09-07 16:59:51 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 17:00:44 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 18:22:24 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 18:55:02 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 19:04:00 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 19:12:41 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 19:13:38 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 19:13:44 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 19:27:04 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:22:02 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:26:41 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:30:24 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:30:30 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:30:40 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:44:31 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:45:35 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:45:53 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:48:32 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:48:41 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:48:45 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:48:55 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:48:56 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:03 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:05 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:09 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:10 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:10 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:12 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:15 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]
2017-09-07 20:49:19 --- ERROR: ErrorException [ 1 ]: Uncaught TypeError: Argument 1 passed to Exceptionhandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/application/classes/exceptionhandler.php:5
Stack trace:
#0 [internal function]: Exceptionhandler::handle(Object(Error))
#1 {main}
  thrown ~ APPPATH/classes/exceptionhandler.php [ 5 ]